import type { Request, Response, NextFunction } from 'express';
import * as svc from '../services/equ-inspection2-sop-steps.service';
import { CreateEquInsp2SopStepSchema, UpdateEquInsp2SopStepSchema, EquInsp2ImportPayloadSchema } from '../validation/equ-inspection2-sop-steps.schemas';
const p = (req: Request, n: string) => { const v = req.params[n]; return Array.isArray(v) ? v[0] : v; };
export async function listController(req: Request, res: Response, next: NextFunction): Promise<void> { try { const t = typeof req.query.cleaningTypeId === 'string' ? req.query.cleaningTypeId.trim() : undefined; const s = typeof req.query.status === 'string' ? req.query.status.trim() : undefined; res.json({ success: true, data: await svc.listEquInsp2SopSteps(req.user!.schemaName, t || undefined, s || undefined) }); } catch (err) { next(err); } }
export async function exportController(req: Request, res: Response, next: NextFunction): Promise<void> { try { const t = typeof req.query.cleaningTypeId === 'string' ? req.query.cleaningTypeId.trim() : undefined; await svc.streamEquInsp2SopStepsCsv(req.user!.schemaName, res, t || undefined); } catch (err) { if (!res.headersSent) next(err); else res.end(); } }
export async function importController(req: Request, res: Response, next: NextFunction): Promise<void> { try { const { rows } = EquInsp2ImportPayloadSchema.parse(req.body); res.json({ success: true, data: await svc.importEquInsp2SopSteps(rows, req.user!.schemaName, req.user!.id) }); } catch (err) { next(err); } }
export async function getController(req: Request, res: Response, next: NextFunction): Promise<void> { try { res.json({ success: true, data: await svc.getEquInsp2SopStep(p(req, 'id'), req.user!.schemaName) }); } catch (err) { next(err); } }
export async function createController(req: Request, res: Response, next: NextFunction): Promise<void> { try { const dto = CreateEquInsp2SopStepSchema.parse(req.body); res.status(201).json({ success: true, data: await svc.createEquInsp2SopStep(dto, req.user!.schemaName, req.user!.id) }); } catch (err) { next(err); } }
export async function updateController(req: Request, res: Response, next: NextFunction): Promise<void> { try { const dto = UpdateEquInsp2SopStepSchema.parse(req.body); res.json({ success: true, data: await svc.updateEquInsp2SopStep(p(req, 'id'), dto, req.user!.schemaName, req.user!.id) }); } catch (err) { next(err); } }
export async function deleteController(req: Request, res: Response, next: NextFunction): Promise<void> { try { await svc.deleteEquInsp2SopStep(p(req, 'id'), req.user!.schemaName); res.json({ success: true }); } catch (err) { next(err); } }
