CREATE TABLE IF NOT EXISTS tenant_medsync.room_types (
 
    -- Internal UUID — used as FK in rooms table
    id                  UUID            PRIMARY KEY DEFAULT uuid_generate_v4(),
 
    -- Human-readable identifier shown in the UI
    -- Format: RT-001, RT-002 etc.
    -- Generated by the application, not auto-incremented
    -- because the client may want to control the numbering
    room_type_id        VARCHAR(20)     NOT NULL UNIQUE,
 
    -- Full name of the room type
    -- e.g. "Granulation Room", "Quality Control Room"
    room_type_name      VARCHAR(150)    NOT NULL UNIQUE,
 
    -- Optional long description explaining what this room type is for
    -- Shown as a tooltip or detail in the UI
    room_type_details   TEXT            NULL,
 
    -- Display order in dropdowns and lists
    -- Lower number appears first
    -- Allows admin to control ordering without renaming IDs
    display_order       INT             NOT NULL DEFAULT 0,
 
    -- FALSE = soft-deleted, hidden from UI but data preserved
    -- We never hard-delete master data — it may be referenced
    -- by historical room records or cleaning logs
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
 
    -- ── AUDIT FIELDS ─────────────────────────────────────────
    -- Who created and last modified this record
    -- References users.id in the same tenant schema
    created_by          UUID            NULL REFERENCES tenant_medsync.users(id)
                                            ON DELETE SET NULL,
 
    updated_by          UUID            NULL REFERENCES tenant_medsync.users(id)
                                            ON DELETE SET NULL,
 
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
 
);